version: "3.8"

services:

  api:
 
    build:
      context: .
      dockerfile: docker/api/Dockerfile

    volumes:
      - ./volume/data:/usr/src/app/volume
 
    ports:
      - 7329:8000

    command: bash -c "poetry run uvicorn app:create_app --host 0.0.0.0 --port 8000"
  ml:
    build:
      context: .
      dockerfile: docker/ml/Dockerfile

    volumes:
      - ./volume/data:/usr/src/app/volume
 
    ports:
      - 5771:8000

    command: bash -c "poetry run python ml/run.py" #"sleep 10000"
  
networks:
  default:
    external: true
    name: shared-api-network
