version: "3"

services:

  server:
 
    build: server/
    working_dir: /app
    # command: python server/fastapi_app.py
    entrypoint: /bin/bash
    tty: true
    volumes:
      - /home/boris/Projects/Virtual Wardrobe/server:/app/server
      - /home/boris/Projects/Virtual Wardrobe/data:/app/data
      
  # volumes:
  #   - ./:/app
    ports:
      - 7330:1234
  # # Второй сервис (контейнер): клиент.
  # # Этот сервис назван 'client'.

  # client:
  #   # Здесь 'client/ соответствует пути к папке, которая содержит
  #   # файл Dockerfile для клиентской части системы.

  #   build: client/

  #   # Команда, которую нужно запустить после создания образа.
  #   # Следующая команда означает запуск "python ./client.py".
 
  #   command: python ./client.py

  #   # Ключевое слово 'network_mode' используется для описания типа сети.
  #   # Тут мы указываем то, что контейнер может обращаться к 'localhost' компьютера.

  #   network_mode: host

  #   # Ключевое слово 'depends_on' позволяет указывать, должен ли сервис,
  #   # прежде чем запуститься, ждать, когда будут готовы к работе другие сервисы.
  #   # Нам нужно, чтобы сервис 'client' дождался бы готовности к работе сервиса 'server'.
 
  #   depends_on:
  #     - server