version: "3.8"

services:

  api:
 
    build:
      context: .
      dockerfile: docker/api/Dockerfile

    volumes:
      - ./volume/data:/usr/src/app/volume
 
    ports:
      - 7329:8000

    command: bash -c "poetry run uvicorn app:create_app --host 0.0.0.0 --port 8000"
  ml_dev:
    build:
      context: .
      dockerfile: docker/ml/Dockerfile
    deploy: # nvidia settings
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

    volumes:
      # - ./volume/data:/usr/src/app/volume
      - .:/usr/src/app/
    ports:
      - 5771:8000

    command: bash -c "sleep 1000000" # "poetry run python ml/run.py" #"sleep 10000"
  
networks:
  default:
    external: true
    name: shared-api-network
